// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.curso.android.gerenciadortarefas.model;

import br.com.curso.android.gerenciadortarefas.model.Tarefa;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Tarefa_Roo_Configurable {
    
    declare @type: Tarefa: @Configurable;
    
}
